events {}

http {
    server {
        listen 80;

        location / {
            # Docker DNS — резолвит service name во все IP реплик
            resolver 127.0.0.11 valid=10s;
            set $backend "api:8080";
            proxy_pass http://$backend;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
